service: portfolio-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  region: ap-south-1



functions:
  getProject:
    ${file(handlers/get-project.yml)}




plugins:
  - serverless-iam-roles-per-function