service: portfolio-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  region: ap-south-1



functions:
  hello:
    handler: handler.hello
